# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 491)
        MainWindow.setIconSize(QtCore.QSize(35, 35))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.uiMainHLay = QtWidgets.QHBoxLayout()
        self.uiMainHLay.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.uiMainHLay.setContentsMargins(-1, 0, -1, -1)
        self.uiMainHLay.setSpacing(0)
        self.uiMainHLay.setObjectName("uiMainHLay")
        self.gridLayout.addLayout(self.uiMainHLay, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1039, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuAkten = QtWidgets.QMenu(self.menuBar)
        self.menuAkten.setObjectName("menuAkten")
        self.menuWerkzeuge = QtWidgets.QMenu(self.menuBar)
        self.menuWerkzeuge.setObjectName("menuWerkzeuge")
        self.menuGrundst_cke = QtWidgets.QMenu(self.menuBar)
        self.menuGrundst_cke.setObjectName("menuGrundst_cke")
        self.menuOptionen = QtWidgets.QMenu(self.menuBar)
        self.menuOptionen.setObjectName("menuOptionen")
        self.menuKontakte = QtWidgets.QMenu(self.menuBar)
        self.menuKontakte.setObjectName("menuKontakte")
        MainWindow.setMenuBar(self.menuBar)
        self.uiMainToolBar = QtWidgets.QToolBar(MainWindow)
        self.uiMainToolBar.setObjectName("uiMainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.uiMainToolBar)
        self.uiStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.uiStatusBar.setObjectName("uiStatusBar")
        MainWindow.setStatusBar(self.uiStatusBar)
        self.uiAkteAllAction = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/resources/icons/akte.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAkteAllAction.setIcon(icon)
        self.uiAkteAllAction.setObjectName("uiAkteAllAction")
        self.actionCutGstVersionKomplexe = QtWidgets.QAction(MainWindow)
        self.actionCutGstVersionKomplexe.setObjectName("actionCutGstVersionKomplexe")
        self.actionAllGst = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svg/resources/icons/gst_all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAllGst.setIcon(icon1)
        self.actionAllGst.setObjectName("actionAllGst")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/svg/resources/icons/mActionOptions.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon2)
        self.actionSettings.setObjectName("actionSettings")
        self.uiKontakteAllAction = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/svg/resources/icons/contacts.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiKontakteAllAction.setIcon(icon3)
        self.uiKontakteAllAction.setObjectName("uiKontakteAllAction")
        self.menuAkten.addAction(self.uiAkteAllAction)
        self.menuWerkzeuge.addAction(self.actionCutGstVersionKomplexe)
        self.menuGrundst_cke.addAction(self.actionAllGst)
        self.menuOptionen.addAction(self.actionSettings)
        self.menuKontakte.addAction(self.uiKontakteAllAction)
        self.menuBar.addAction(self.menuAkten.menuAction())
        self.menuBar.addAction(self.menuGrundst_cke.menuAction())
        self.menuBar.addAction(self.menuKontakte.menuAction())
        self.menuBar.addAction(self.menuWerkzeuge.menuAction())
        self.menuBar.addAction(self.menuOptionen.menuAction())
        self.uiMainToolBar.addAction(self.uiAkteAllAction)
        self.uiMainToolBar.addAction(self.uiKontakteAllAction)
        self.uiMainToolBar.addAction(self.actionAllGst)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NÖ Alm- und Weidebuch"))
        self.menuAkten.setTitle(_translate("MainWindow", "Akten"))
        self.menuWerkzeuge.setTitle(_translate("MainWindow", "Werkzeuge"))
        self.menuGrundst_cke.setTitle(_translate("MainWindow", "Grundstücke"))
        self.menuOptionen.setTitle(_translate("MainWindow", "Optionen"))
        self.menuKontakte.setTitle(_translate("MainWindow", "Kontakte"))
        self.uiAkteAllAction.setText(_translate("MainWindow", "Alle Akte"))
        self.actionCutGstVersionKomplexe.setText(_translate("MainWindow", "Verschnitt: Gst im AW-Buch und Komplexe"))
        self.actionAllGst.setText(_translate("MainWindow", "Alle zugeordeten Grundstücke"))
        self.actionSettings.setText(_translate("MainWindow", "Einstellungen"))
        self.uiKontakteAllAction.setText(_translate("MainWindow", "alle Kontakte"))
from . import resources_rc
