# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings_general_wdg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneralSettingsPage(object):
    def setupUi(self, GeneralSettingsPage):
        GeneralSettingsPage.setObjectName("GeneralSettingsPage")
        GeneralSettingsPage.resize(562, 417)
        self.gridLayout = QtWidgets.QGridLayout(GeneralSettingsPage)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(GeneralSettingsPage)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(GeneralSettingsPage)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(GeneralSettingsPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(GeneralSettingsPage)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(GeneralSettingsPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(GeneralSettingsPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(GeneralSettingsPage)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(GeneralSettingsPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(GeneralSettingsPage)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(GeneralSettingsPage)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.uiInfoTest = AlmInfoButtonGui(GeneralSettingsPage)
        self.uiInfoTest.setObjectName("uiInfoTest")
        self.horizontalLayout.addWidget(self.uiInfoTest)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(GeneralSettingsPage)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)

        self.retranslateUi(GeneralSettingsPage)
        QtCore.QMetaObject.connectSlotsByName(GeneralSettingsPage)

    def retranslateUi(self, GeneralSettingsPage):
        _translate = QtCore.QCoreApplication.translate
        GeneralSettingsPage.setWindowTitle(_translate("GeneralSettingsPage", "Form"))
        self.checkBox.setText(_translate("GeneralSettingsPage", "CheckBox"))
        self.pushButton.setText(_translate("GeneralSettingsPage", "PushButton"))
        self.label_5.setText(_translate("GeneralSettingsPage", "TextLabel"))
        self.label_3.setText(_translate("GeneralSettingsPage", "TextLabel"))
        self.label_2.setText(_translate("GeneralSettingsPage", "TextLabel"))
        self.label_4.setText(_translate("GeneralSettingsPage", "TextLabel"))
        self.label.setText(_translate("GeneralSettingsPage", "sssss algemein"))
from almgis.gui.info_button_gui import AlmInfoButtonGui
