# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings_colors_wdg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlmSettingsAlmgis(object):
    def setupUi(self, AlmSettingsAlmgis):
        AlmSettingsAlmgis.setObjectName("AlmSettingsAlmgis")
        AlmSettingsAlmgis.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlmSettingsAlmgis)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mGroupBox = QgsCollapsibleGroupBox(AlmSettingsAlmgis)
        self.mGroupBox.setObjectName("mGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.mGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.mGroupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mColorButton = QgsColorButton(self.mGroupBox)
        self.mColorButton.setObjectName("mColorButton")
        self.horizontalLayout.addWidget(self.mColorButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.mGroupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.mGroupBox)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(AlmSettingsAlmgis)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mGroupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.mGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.mGroupBox_2)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/icons/mActionFileOpen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.widget_2 = QtWidgets.QWidget(self.mGroupBox_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.mGroupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(AlmSettingsAlmgis)
        QtCore.QMetaObject.connectSlotsByName(AlmSettingsAlmgis)

    def retranslateUi(self, AlmSettingsAlmgis):
        _translate = QtCore.QCoreApplication.translate
        AlmSettingsAlmgis.setWindowTitle(_translate("AlmSettingsAlmgis", "Form"))
        self.mGroupBox.setTitle(_translate("AlmSettingsAlmgis", "Farben"))
        self.label.setText(_translate("AlmSettingsAlmgis", "ausgewählte Elemente:"))
        self.mGroupBox_2.setTitle(_translate("AlmSettingsAlmgis", "Stildateien"))
        self.label_2.setText(_translate("AlmSettingsAlmgis", "Koppeln:"))
        self.label_3.setText(_translate("AlmSettingsAlmgis", "TextLabel"))
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgscolorbutton import QgsColorButton
from . import resources_rc
