#!/bin/sh

# convert the resouce-file using linux
pyrcc5 resources.qrc -o ui_py/resources_rc.py

# pyuic5 --from-imports ui/mainwindow.ui -o ui_py/mainwindow_UI.py

pyuic5 --from-imports ui/kontakt/kontakt.ui -o ui_py/kontakt/kontakt_UI.py
