# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/entity_titel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EntityTitel(object):
    def setupUi(self, EntityTitel):
        EntityTitel.setObjectName("EntityTitel")
        EntityTitel.resize(802, 47)
        self.horizontalLayout = QtWidgets.QHBoxLayout(EntityTitel)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiTitelLbl = QtWidgets.QLabel(EntityTitel)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.uiTitelLbl.setFont(font)
        self.uiTitelLbl.setObjectName("uiTitelLbl")
        self.horizontalLayout.addWidget(self.uiTitelLbl)
        spacerItem = QtWidgets.QSpacerItem(622, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiEntityTools = QtWidgets.QToolButton(EntityTitel)
        self.uiEntityTools.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/resources/icons/hamburger.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiEntityTools.setIcon(icon)
        self.uiEntityTools.setIconSize(QtCore.QSize(40, 40))
        self.uiEntityTools.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.uiEntityTools.setAutoRaise(True)
        self.uiEntityTools.setArrowType(QtCore.Qt.NoArrow)
        self.uiEntityTools.setObjectName("uiEntityTools")
        self.horizontalLayout.addWidget(self.uiEntityTools)

        self.retranslateUi(EntityTitel)
        QtCore.QMetaObject.connectSlotsByName(EntityTitel)

    def retranslateUi(self, EntityTitel):
        _translate = QtCore.QCoreApplication.translate
        EntityTitel.setWindowTitle(_translate("EntityTitel", "Form"))
        self.uiTitelLbl.setText(_translate("EntityTitel", "TextLabel"))
import resources_rc
