# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/footer_line.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FooterLine(object):
    def setupUi(self, FooterLine):
        FooterLine.setObjectName("FooterLine")
        FooterLine.resize(365, 34)
        FooterLine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FooterLine)
        self.horizontalLayout.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiLabelLbl = QtWidgets.QLabel(FooterLine)
        self.uiLabelLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiLabelLbl.setObjectName("uiLabelLbl")
        self.horizontalLayout.addWidget(self.uiLabelLbl)
        self.uiValueLbl = QtWidgets.QLineEdit(FooterLine)
        self.uiValueLbl.setEnabled(True)
        self.uiValueLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiValueLbl.setReadOnly(True)
        self.uiValueLbl.setObjectName("uiValueLbl")
        self.horizontalLayout.addWidget(self.uiValueLbl)
        self.uiUnitLbl = QtWidgets.QLabel(FooterLine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiUnitLbl.sizePolicy().hasHeightForWidth())
        self.uiUnitLbl.setSizePolicy(sizePolicy)
        self.uiUnitLbl.setMinimumSize(QtCore.QSize(10, 0))
        self.uiUnitLbl.setMaximumSize(QtCore.QSize(50, 16777215))
        self.uiUnitLbl.setObjectName("uiUnitLbl")
        self.horizontalLayout.addWidget(self.uiUnitLbl)

        self.retranslateUi(FooterLine)
        QtCore.QMetaObject.connectSlotsByName(FooterLine)

    def retranslateUi(self, FooterLine):
        _translate = QtCore.QCoreApplication.translate
        FooterLine.setWindowTitle(_translate("FooterLine", "Form"))
        self.uiLabelLbl.setText(_translate("FooterLine", "TextLabel"))
        self.uiUnitLbl.setText(_translate("FooterLine", "unit"))
