# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiTitleLbl = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTitleLbl.sizePolicy().hasHeightForWidth())
        self.uiTitleLbl.setSizePolicy(sizePolicy)
        self.uiTitleLbl.setObjectName("uiTitleLbl")
        self.verticalLayout_2.addWidget(self.uiTitleLbl)
        self.line = QtWidgets.QFrame(MainWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.uiMainVLay = QtWidgets.QVBoxLayout()
        self.uiMainVLay.setObjectName("uiMainVLay")
        self.verticalLayout_2.addLayout(self.uiMainVLay)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Form"))
        self.uiTitleLbl.setText(_translate("MainWidget", "TextLabel"))
