# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 493)
        MainWindow.setIconSize(QtCore.QSize(35, 35))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.uiMainHLay = QtWidgets.QHBoxLayout()
        self.uiMainHLay.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.uiMainHLay.setContentsMargins(-1, 0, -1, -1)
        self.uiMainHLay.setSpacing(0)
        self.uiMainHLay.setObjectName("uiMainHLay")
        self.gridLayout.addLayout(self.uiMainHLay, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1039, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuAkten = QtWidgets.QMenu(self.menuBar)
        self.menuAkten.setObjectName("menuAkten")
        self.menuWerkzeuge = QtWidgets.QMenu(self.menuBar)
        self.menuWerkzeuge.setObjectName("menuWerkzeuge")
        self.menuGrundst_cke = QtWidgets.QMenu(self.menuBar)
        self.menuGrundst_cke.setObjectName("menuGrundst_cke")
        MainWindow.setMenuBar(self.menuBar)
        self.uiMainToolBar = QtWidgets.QToolBar(MainWindow)
        self.uiMainToolBar.setObjectName("uiMainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.uiMainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.uiAkteAllAction = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/resources/icons/akte.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAkteAllAction.setIcon(icon)
        self.uiAkteAllAction.setObjectName("uiAkteAllAction")
        self.actionCutGstVersionKomplexe = QtWidgets.QAction(MainWindow)
        self.actionCutGstVersionKomplexe.setObjectName("actionCutGstVersionKomplexe")
        self.uiAactionAllMatchGst = QtWidgets.QAction(MainWindow)
        self.uiAactionAllMatchGst.setObjectName("uiAactionAllMatchGst")
        self.menuAkten.addAction(self.uiAkteAllAction)
        self.menuWerkzeuge.addAction(self.actionCutGstVersionKomplexe)
        self.menuGrundst_cke.addAction(self.uiAactionAllMatchGst)
        self.menuBar.addAction(self.menuAkten.menuAction())
        self.menuBar.addAction(self.menuGrundst_cke.menuAction())
        self.menuBar.addAction(self.menuWerkzeuge.menuAction())
        self.uiMainToolBar.addAction(self.uiAkteAllAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NÖ Alm- und Weidebuch"))
        self.menuAkten.setTitle(_translate("MainWindow", "Akten"))
        self.menuWerkzeuge.setTitle(_translate("MainWindow", "Werkzeuge"))
        self.menuGrundst_cke.setTitle(_translate("MainWindow", "Grundstücke"))
        self.uiAkteAllAction.setText(_translate("MainWindow", "Alle Akte"))
        self.actionCutGstVersionKomplexe.setText(_translate("MainWindow", "Verschnitt: Gst im AW-Buch und Komplexe"))
        self.uiAactionAllMatchGst.setText(_translate("MainWindow", "Alle zugeordeten Grundstücke"))
import resources_rc
