# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/scopes/gst/gst_version_eigentuemer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GstEigentuemer(object):
    def setupUi(self, GstEigentuemer):
        GstEigentuemer.setObjectName("GstEigentuemer")
        GstEigentuemer.resize(683, 42)
        self.verticalLayout = QtWidgets.QVBoxLayout(GstEigentuemer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.uiNameLbl = QtWidgets.QLabel(GstEigentuemer)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uiNameLbl.setFont(font)
        self.uiNameLbl.setObjectName("uiNameLbl")
        self.gridLayout.addWidget(self.uiNameLbl, 0, 1, 1, 1)
        self.uiAdresseLbl = QtWidgets.QLabel(GstEigentuemer)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.uiAdresseLbl.setFont(font)
        self.uiAdresseLbl.setObjectName("uiAdresseLbl")
        self.gridLayout.addWidget(self.uiAdresseLbl, 1, 1, 1, 1)
        self.uiAnteilLbl = QtWidgets.QLabel(GstEigentuemer)
        self.uiAnteilLbl.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.uiAnteilLbl.setFont(font)
        self.uiAnteilLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiAnteilLbl.setObjectName("uiAnteilLbl")
        self.gridLayout.addWidget(self.uiAnteilLbl, 0, 0, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(GstEigentuemer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.retranslateUi(GstEigentuemer)
        QtCore.QMetaObject.connectSlotsByName(GstEigentuemer)

    def retranslateUi(self, GstEigentuemer):
        _translate = QtCore.QCoreApplication.translate
        GstEigentuemer.setWindowTitle(_translate("GstEigentuemer", "Form"))
        self.uiNameLbl.setText(_translate("GstEigentuemer", "TextLabel"))
        self.uiAdresseLbl.setText(_translate("GstEigentuemer", "TextLabel"))
        self.uiAnteilLbl.setText(_translate("GstEigentuemer", "TextLabel"))
