# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/scopes/gst/gst.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gst(object):
    def setupUi(self, Gst):
        Gst.setObjectName("Gst")
        Gst.resize(888, 600)
        self.centralwidget = QtWidgets.QWidget(Gst)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.uiGstLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.uiGstLbl.setFont(font)
        self.uiGstLbl.setObjectName("uiGstLbl")
        self.gridLayout.addWidget(self.uiGstLbl, 0, 1, 1, 1)
        self.uiKgLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.uiKgLbl.setFont(font)
        self.uiKgLbl.setObjectName("uiKgLbl")
        self.gridLayout.addWidget(self.uiKgLbl, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.uiGstVersionTab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.uiGstVersionTab.setFont(font)
        self.uiGstVersionTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.uiGstVersionTab.setObjectName("uiGstVersionTab")
        self.uiAktuellWdg = QtWidgets.QWidget()
        self.uiAktuellWdg.setObjectName("uiAktuellWdg")
        self.uiGstVersionTab.addTab(self.uiAktuellWdg, "")
        self.verticalLayout.addWidget(self.uiGstVersionTab)
        Gst.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Gst)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        Gst.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gst)
        self.statusbar.setObjectName("statusbar")
        Gst.setStatusBar(self.statusbar)

        self.retranslateUi(Gst)
        self.uiGstVersionTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gst)

    def retranslateUi(self, Gst):
        _translate = QtCore.QCoreApplication.translate
        Gst.setWindowTitle(_translate("Gst", "MainWindow"))
        self.label_3.setText(_translate("Gst", "Grundstücksinformationen:"))
        self.label.setText(_translate("Gst", "Nummer:"))
        self.label_2.setText(_translate("Gst", "KG:"))
        self.uiGstLbl.setText(_translate("Gst", "TextLabel"))
        self.uiKgLbl.setText(_translate("Gst", "TextLabel"))
        self.uiGstVersionTab.setTabText(self.uiGstVersionTab.indexOf(self.uiAktuellWdg), _translate("Gst", "aktuell"))
