# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/scopes/gst/gst_zuordnung.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GstZuordnung(object):
    def setupUi(self, GstZuordnung):
        GstZuordnung.setObjectName("GstZuordnung")
        GstZuordnung.resize(910, 688)
        self.centralwidget = QtWidgets.QWidget(GstZuordnung)
        self.centralwidget.setObjectName("centralwidget")
        self.uiCentralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.uiCentralLayout.setObjectName("uiCentralLayout")
        self.uiHeaderHlay = QtWidgets.QHBoxLayout()
        self.uiHeaderHlay.setObjectName("uiHeaderHlay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.uiHeaderHlay.addWidget(self.label)
        self.uiGdbDataTimeLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.uiGdbDataTimeLbl.setFont(font)
        self.uiGdbDataTimeLbl.setObjectName("uiGdbDataTimeLbl")
        self.uiHeaderHlay.addWidget(self.uiGdbDataTimeLbl)
        self.uiLoadGdbPbtn = QtWidgets.QPushButton(self.centralwidget)
        self.uiLoadGdbPbtn.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.uiLoadGdbPbtn.setFont(font)
        self.uiLoadGdbPbtn.setObjectName("uiLoadGdbPbtn")
        self.uiHeaderHlay.addWidget(self.uiLoadGdbPbtn)
        self.uiOpenImpPathPbtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiOpenImpPathPbtn.sizePolicy().hasHeightForWidth())
        self.uiOpenImpPathPbtn.setSizePolicy(sizePolicy)
        self.uiOpenImpPathPbtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/resources/icons/mActionFileOpen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiOpenImpPathPbtn.setIcon(icon)
        self.uiOpenImpPathPbtn.setIconSize(QtCore.QSize(25, 25))
        self.uiOpenImpPathPbtn.setFlat(True)
        self.uiOpenImpPathPbtn.setObjectName("uiOpenImpPathPbtn")
        self.uiHeaderHlay.addWidget(self.uiOpenImpPathPbtn)
        self.uiCentralLayout.addLayout(self.uiHeaderHlay)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.uiCentralLayout.addWidget(self.line)
        GstZuordnung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GstZuordnung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 21))
        self.menubar.setObjectName("menubar")
        GstZuordnung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GstZuordnung)
        self.statusbar.setObjectName("statusbar")
        GstZuordnung.setStatusBar(self.statusbar)

        self.retranslateUi(GstZuordnung)
        QtCore.QMetaObject.connectSlotsByName(GstZuordnung)

    def retranslateUi(self, GstZuordnung):
        _translate = QtCore.QCoreApplication.translate
        GstZuordnung.setWindowTitle(_translate("GstZuordnung", "MainWindow"))
        self.label.setText(_translate("GstZuordnung", "GDB-Daten zuletzt eingelesen:"))
        self.uiGdbDataTimeLbl.setText(_translate("GstZuordnung", "TextLabel"))
        self.uiLoadGdbPbtn.setText(_translate("GstZuordnung", "GDB-Daten einlesen"))
import resources_rc
