# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_core/entity_titel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EntityTitel(object):
    def setupUi(self, EntityTitel):
        EntityTitel.setObjectName("EntityTitel")
        EntityTitel.resize(802, 31)
        self.horizontalLayout = QtWidgets.QHBoxLayout(EntityTitel)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiTitelLbl = QtWidgets.QLabel(EntityTitel)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uiTitelLbl.setFont(font)
        self.uiTitelLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTitelLbl.setObjectName("uiTitelLbl")
        self.horizontalLayout.addWidget(self.uiTitelLbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(EntityTitel)
        QtCore.QMetaObject.connectSlotsByName(EntityTitel)

    def retranslateUi(self, EntityTitel):
        _translate = QtCore.QCoreApplication.translate
        EntityTitel.setWindowTitle(_translate("EntityTitel", "Form"))
        self.uiTitelLbl.setText(_translate("EntityTitel", "TextLabel"))
import resources_rc
