# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_core/filter_element.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterElement(object):
    def setupUi(self, FilterElement):
        FilterElement.setObjectName("FilterElement")
        FilterElement.resize(233, 22)
        self.uiFilterElementLay = QtWidgets.QHBoxLayout(FilterElement)
        self.uiFilterElementLay.setContentsMargins(2, 2, 2, 2)
        self.uiFilterElementLay.setSpacing(4)
        self.uiFilterElementLay.setObjectName("uiFilterElementLay")
        self.uiLabelLbl = QtWidgets.QLabel(FilterElement)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.uiLabelLbl.setFont(font)
        self.uiLabelLbl.setObjectName("uiLabelLbl")
        self.uiFilterElementLay.addWidget(self.uiLabelLbl)

        self.retranslateUi(FilterElement)
        QtCore.QMetaObject.connectSlotsByName(FilterElement)

    def retranslateUi(self, FilterElement):
        _translate = QtCore.QCoreApplication.translate
        FilterElement.setWindowTitle(_translate("FilterElement", "Form"))
        self.uiLabelLbl.setText(_translate("FilterElement", "TextLabel"))
