# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_core/main_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(375, 91)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MainDialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiMessagesVlay = QtWidgets.QVBoxLayout()
        self.uiMessagesVlay.setSpacing(0)
        self.uiMessagesVlay.setObjectName("uiMessagesVlay")
        self.verticalLayout_2.addLayout(self.uiMessagesVlay)
        self.uiWidgetsVlay = QtWidgets.QVBoxLayout()
        self.uiWidgetsVlay.setContentsMargins(0, -1, 0, -1)
        self.uiWidgetsVlay.setObjectName("uiWidgetsVlay")
        self.verticalLayout_2.addLayout(self.uiWidgetsVlay)
        self.uiButtonsHlay = QtWidgets.QHBoxLayout()
        self.uiButtonsHlay.setContentsMargins(6, 6, 6, 6)
        self.uiButtonsHlay.setObjectName("uiButtonsHlay")
        self.verticalLayout_2.addLayout(self.uiButtonsHlay)

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "NÖ Alm- und Weidebuch"))
