# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/print_content_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintContentWidget(object):
    def setupUi(self, PrintContentWidget):
        PrintContentWidget.setObjectName("PrintContentWidget")
        PrintContentWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PrintContentWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(PrintContentWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiContentLedit = QtWidgets.QLineEdit(PrintContentWidget)
        self.uiContentLedit.setObjectName("uiContentLedit")
        self.gridLayout.addWidget(self.uiContentLedit, 0, 1, 1, 1)
        self.uiRemarkTedit = QtWidgets.QPlainTextEdit(PrintContentWidget)
        self.uiRemarkTedit.setTabChangesFocus(True)
        self.uiRemarkTedit.setObjectName("uiRemarkTedit")
        self.gridLayout.addWidget(self.uiRemarkTedit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(PrintContentWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.uiUserLedit = QtWidgets.QLineEdit(PrintContentWidget)
        self.uiUserLedit.setObjectName("uiUserLedit")
        self.gridLayout.addWidget(self.uiUserLedit, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(PrintContentWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(PrintContentWidget)
        QtCore.QMetaObject.connectSlotsByName(PrintContentWidget)

    def retranslateUi(self, PrintContentWidget):
        _translate = QtCore.QCoreApplication.translate
        PrintContentWidget.setWindowTitle(_translate("PrintContentWidget", "Form"))
        self.label.setText(_translate("PrintContentWidget", "Gegenstand:"))
        self.label_3.setText(_translate("PrintContentWidget", "Bearbeiter:"))
        self.label_2.setText(_translate("PrintContentWidget", "Anmerkung:"))
