# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/scopes/komplex/komplex_dataform.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KomplexDataForm(object):
    def setupUi(self, KomplexDataForm):
        KomplexDataForm.setObjectName("KomplexDataForm")
        KomplexDataForm.resize(497, 260)
        self.centralwidget = QtWidgets.QWidget(KomplexDataForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.uiAnmerkung = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.uiAnmerkung.setObjectName("uiAnmerkung")
        self.gridLayout.addWidget(self.uiAnmerkung, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiBearbeiter = QtWidgets.QLineEdit(self.centralwidget)
        self.uiBearbeiter.setClearButtonEnabled(True)
        self.uiBearbeiter.setObjectName("uiBearbeiter")
        self.gridLayout.addWidget(self.uiBearbeiter, 3, 1, 1, 1)
        self.uiNr = QtWidgets.QSpinBox(self.centralwidget)
        self.uiNr.setMaximumSize(QtCore.QSize(70, 16777215))
        self.uiNr.setMinimum(1)
        self.uiNr.setMaximum(9999)
        self.uiNr.setObjectName("uiNr")
        self.gridLayout.addWidget(self.uiNr, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.uiName = QtWidgets.QLineEdit(self.centralwidget)
        self.uiName.setClearButtonEnabled(True)
        self.uiName.setObjectName("uiName")
        self.gridLayout.addWidget(self.uiName, 1, 1, 1, 1)
        self.uiJahr = QtWidgets.QSpinBox(self.centralwidget)
        self.uiJahr.setMaximumSize(QtCore.QSize(70, 16777215))
        self.uiJahr.setMinimum(1900)
        self.uiJahr.setMaximum(2100)
        self.uiJahr.setObjectName("uiJahr")
        self.gridLayout.addWidget(self.uiJahr, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        KomplexDataForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KomplexDataForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 21))
        self.menubar.setObjectName("menubar")
        KomplexDataForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KomplexDataForm)
        self.statusbar.setObjectName("statusbar")
        KomplexDataForm.setStatusBar(self.statusbar)

        self.retranslateUi(KomplexDataForm)
        QtCore.QMetaObject.connectSlotsByName(KomplexDataForm)
        KomplexDataForm.setTabOrder(self.uiNr, self.uiName)
        KomplexDataForm.setTabOrder(self.uiName, self.uiJahr)
        KomplexDataForm.setTabOrder(self.uiJahr, self.uiBearbeiter)
        KomplexDataForm.setTabOrder(self.uiBearbeiter, self.uiAnmerkung)

    def retranslateUi(self, KomplexDataForm):
        _translate = QtCore.QCoreApplication.translate
        KomplexDataForm.setWindowTitle(_translate("KomplexDataForm", "MainWindow"))
        self.label_2.setText(_translate("KomplexDataForm", "Name:"))
        self.label_5.setText(_translate("KomplexDataForm", "Anmerkung:"))
        self.label.setText(_translate("KomplexDataForm", "Nr:"))
        self.label_3.setText(_translate("KomplexDataForm", "Jahr:"))
        self.label_6.setText(_translate("KomplexDataForm", "Bearbeiter:"))
